package: uppy
version: '0.0.1-alpha0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/demo_addon

page:
    title: 'translate:title' # Werte die mit `translate:` beginnen, werden anhand der Sprachdatei 체bersetzt. Der Addon-Pr채fix (hier `demo_addon_`) kann weggelassen werden.
    perm: admin # Seite ist nur f체r Admins erreichbar
    # Unterseiten
    subpages:
        main:
            title: 'translate:main'
            perm: demo_addon[] # Das AddOn stellt ein Benutzerrecht bereit, das aktiviert sein muss, um diese Unterseite zu erreichen. Admins haben alle Rechte.
        config:
            title: 'translate:config'
            perm: demo_addon[config] # Das noch spezifischer AddOn-Benutzerrecht 'config' ist f체r diese Unterseite erforderlich. Admins haben alle Rechte.
            icon: rex-icon fa-wrench # Icon von Font Awesome

requires:
    redaxo: '^5.7'
    php:
        version: '>=7.1'

installer_ignore:
    - node_modules
    - .env
