package: uppy
version: '0.0.1-alpha1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/uppy

page:
    title: 'translate:uppy_title'
    perm: admin
    subpages:
        main:
            title: 'translate:main'
            perm: uppy_addon[]
        config:
            title: 'translate:config'
            perm: uppy_addon[config] # Das noch spezifischer AddOn-Benutzerrecht 'config' ist für diese Unterseite erforderlich. Admins haben alle Rechte.
            icon: rex-icon fa-wrench # Icon von Font Awesome

requires:
    redaxo: '^5.7'
    php:
        version: '^7.1'

installer_ignore:
    - node_modules
    - .env
