package: uppy
version: '2.0.0-beta2'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/uppy
requires:
    php: '>=8.1'
    redaxo: '^5.19.1'
    packages:
        metainfo: '>=2.0.0'
page:
    title: 'translate:uppy_title'
    icon: rex-icon fa-solid fa-upload
    perm: uppy[upload]
    subpages:
        upload: { 
            title: 'translate:uppy_upload',
            icon: rex-icon fa-solid fa-cloud-arrow-up,
            perm: uppy[upload]
        }
        demo: { 
            title: 'translate:uppy_demo',
            icon: rex-icon fa-solid fa-flask,
            perm: admin
        }
        settings: { 
            title: 'translate:uppy_settings',
            icon: rex-icon fa-solid fa-gears,
            perm: admin
        }
        help: { 
            title: 'translate:uppy_help',
            icon: rex-icon fa-solid fa-circle-question,
            subPath: README.md, 
            itemClass: 'pull-right' 
        }
        api: { 
            title: 'translate:uppy_api',
            icon: rex-icon fa-solid fa-code,
            subPath: API.md, 
            itemClass: 'pull-right' 
        }
default_config:
    allowed_types: 'image/jpeg,image/png,image/gif,image/webp,image/svg+xml,application/pdf,video/mp4,video/mpeg,video/quicktime,audio/mpeg,audio/wav'
    max_filesize: 200
    max_files: 30
    category_id: 0
    lang: 'de_de'
    enable_chunks: true
    chunk_size: 5
    replace_mediapool: false
    metadata_fields: 'title,med_alt,med_copyright'
    api_token: ''
    enable_resize: true
    resize_width: 2000
    resize_height: 2000
    resize_quality: 85
    fix_exif_orientation: true
    enable_webcam: false
    enable_image_editor: false
    crop_ratios: '1:1,16:9,4:3,3:2,free'
    required_metadata_fields: ''
